test

diff --git a/.github/workflows/build-test-linux.yml b/.github/workflows/build-test-linux.yml
--- a/.github/workflows/build-test-linux.yml
+++ b/.github/workflows/build-test-linux.yml
@@ -69,11 +69,12 @@ jobs:
       - name: Check modified files
         id: check_files
         run: |
-          set -euxo pipefail
-          if [ ${{ github.event.ref }} == refs/tags/v* ]; then
+          # set -euxo pipefail
+          set -x
+          if [ ${{ github.ref }} == refs/tags/v* ]; then
             echo "this is the release tag, always run the full tests"
-          elif [ ${{github.event.ref_type != 'branch' }} ]; then
-            echo "this is ref_type=${{github.event.ref_type}}, always run the full tests "
+          elif [ ${{ github.ref_type }} != 'branch' ]; then
+            echo "this is ref_type=${{ github.event.ref_type }}, always run the full tests "
           else
             echo "=============== last modified files ==============="
             git diff --name-only HEAD^ HEAD
@@ -81,18 +82,18 @@ jobs:
             git diff --name-only github.event.ref main
           fi
 
-          echo "github.event.ref_type: ${{ github.event.ref_type }}"
-          echo "github.event.ref: ${{ github.event.ref }}"
-          echo "github.event.ref_name: ${{ github.event.ref_name }}"
+          echo "github.event_name: ${{ github.event_name }}"
+          echo "github.ref: ${{ github.ref }}"
+          echo "github.ref_name: ${{ github.ref_name }}"
           echo "github.event.master_branch: ${{ github.event.master_branch }}"
-          echo "github.event.pull_request: ${{ github.event.pull_request }}"
-          folder_names="$(python3 scripts/check_files.py)"
-          echo "folder_names=${folder_names}" >> "${GITHUB_OUTPUT}"
+          echo "github.event.pull_request.base.sha: ${{ github.event.pull_request.base.sha }}"
+          echo "github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"
+          echo "folder_names=py/dynamo" >> "${GITHUB_OUTPUT}"
 
   tests-py-torchscript-fe:
     name: Test torchscript frontend [Python]
     needs: [generate-matrix, build, check]
-    if: ${{ contains(needs.check.folder_names, 'tests/modules') }}
+    if: ${{ contains(needs.check.folder_names, 'py/ts') }}
     strategy:
       fail-fast: false
       matrix:
@@ -128,7 +129,7 @@ jobs:
   tests-py-dynamo-converters:
     name: Test dynamo converters [Python]
     needs: [generate-matrix, build, check]
-    if: ${{ contains(needs.check.folder_names, 'tests/py/dynamo') }}
+    if: ${{ contains(needs.check.folder_names, 'py/dynamo') }}
     strategy:
       fail-fast: false
       matrix:
@@ -176,6 +177,8 @@ jobs:
       build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
       pre-script: ${{ matrix.pre-script }}
       script: |
+        set -x
+        echo ${{ needs.check.folder_names }}
         export USE_HOST_DEPS=1
         pushd .
         cd tests/py/dynamo
@@ -183,122 +186,122 @@ jobs:
         python -m pytest --junitxml=${RUNNER_TEST_RESULTS_DIR}/dyn_models_export.xml --ir dynamo models/test_dyn_models.py
         popd
 
-  tests-py-dynamo-serde:
-    name: Test dynamo export serde [Python]
-    needs: [generate-matrix, build]
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - repository: pytorch/tensorrt
-            package-name: torch_tensorrt
-            pre-script: packaging/pre_build_script.sh
-            post-script: packaging/post_build_script.sh
-            smoke-test-script: packaging/smoke_test_script.sh
-    uses: pytorch/tensorrt/.github/workflows/linux-test.yml@main
-    with:
-      job-name: tests-py-dynamo-serde
-      repository: "pytorch/tensorrt"
-      ref: ""
-      test-infra-repository: pytorch/test-infra
-      test-infra-ref: main
-      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
-      pre-script: ${{ matrix.pre-script }}
-      script: |
-        export USE_HOST_DEPS=1
-        pushd .
-        cd tests/py/dynamo
-        python -m pytest --junitxml=${RUNNER_TEST_RESULTS_DIR}/export_serde_test_results.xml --ir dynamo models/test_export_serde.py
-        popd
+  # tests-py-dynamo-serde:
+  #   name: Test dynamo export serde [Python]
+  #   needs: [generate-matrix, build]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - repository: pytorch/tensorrt
+  #           package-name: torch_tensorrt
+  #           pre-script: packaging/pre_build_script.sh
+  #           post-script: packaging/post_build_script.sh
+  #           smoke-test-script: packaging/smoke_test_script.sh
+  #   uses: pytorch/tensorrt/.github/workflows/linux-test.yml@main
+  #   with:
+  #     job-name: tests-py-dynamo-serde
+  #     repository: "pytorch/tensorrt"
+  #     ref: ""
+  #     test-infra-repository: pytorch/test-infra
+  #     test-infra-ref: main
+  #     build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
+  #     pre-script: ${{ matrix.pre-script }}
+  #     script: |
+  #       export USE_HOST_DEPS=1
+  #       pushd .
+  #       cd tests/py/dynamo
+  #       python -m pytest --junitxml=${RUNNER_TEST_RESULTS_DIR}/export_serde_test_results.xml --ir dynamo models/test_export_serde.py
+  #       popd
 
-  tests-py-torch-compile-be:
-    name: Test torch compile backend [Python]
-    needs: [generate-matrix, build]
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - repository: pytorch/tensorrt
-            package-name: torch_tensorrt
-            pre-script: packaging/pre_build_script.sh
-            post-script: packaging/post_build_script.sh
-            smoke-test-script: packaging/smoke_test_script.sh
-    uses: pytorch/tensorrt/.github/workflows/linux-test.yml@main
-    with:
-      job-name: tests-py-torch-compile-be
-      repository: "pytorch/tensorrt"
-      ref: ""
-      test-infra-repository: pytorch/test-infra
-      test-infra-ref: main
-      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
-      pre-script: ${{ matrix.pre-script }}
-      script: |
-        export USE_HOST_DEPS=1
-        pushd .
-        cd tests/py/dynamo
-        python -m pytest -n 10 --junitxml=${RUNNER_TEST_RESULTS_DIR}/torch_compile_be_test_results.xml backend/
-        python -m pytest -n 4 --junitxml=${RUNNER_TEST_RESULTS_DIR}/torch_comple_be_e2e_test_results.xml --ir torch_compile models/test_models.py
-        python -m pytest --junitxml=${RUNNER_TEST_RESULTS_DIR}/torch_compile_dyn_models_export.xml --ir torch_compile models/test_dyn_models.py
-        popd
+  # tests-py-torch-compile-be:
+  #   name: Test torch compile backend [Python]
+  #   needs: [generate-matrix, build]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - repository: pytorch/tensorrt
+  #           package-name: torch_tensorrt
+  #           pre-script: packaging/pre_build_script.sh
+  #           post-script: packaging/post_build_script.sh
+  #           smoke-test-script: packaging/smoke_test_script.sh
+  #   uses: pytorch/tensorrt/.github/workflows/linux-test.yml@main
+  #   with:
+  #     job-name: tests-py-torch-compile-be
+  #     repository: "pytorch/tensorrt"
+  #     ref: ""
+  #     test-infra-repository: pytorch/test-infra
+  #     test-infra-ref: main
+  #     build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
+  #     pre-script: ${{ matrix.pre-script }}
+  #     script: |
+  #       export USE_HOST_DEPS=1
+  #       pushd .
+  #       cd tests/py/dynamo
+  #       python -m pytest -n 10 --junitxml=${RUNNER_TEST_RESULTS_DIR}/torch_compile_be_test_results.xml backend/
+  #       python -m pytest -n 4 --junitxml=${RUNNER_TEST_RESULTS_DIR}/torch_comple_be_e2e_test_results.xml --ir torch_compile models/test_models.py
+  #       python -m pytest --junitxml=${RUNNER_TEST_RESULTS_DIR}/torch_compile_dyn_models_export.xml --ir torch_compile models/test_dyn_models.py
+  #       popd
 
-  tests-py-dynamo-core:
-    name: Test dynamo core [Python]
-    needs: [generate-matrix, build]
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - repository: pytorch/tensorrt
-            package-name: torch_tensorrt
-            pre-script: packaging/pre_build_script.sh
-            post-script: packaging/post_build_script.sh
-            smoke-test-script: packaging/smoke_test_script.sh
-    uses: pytorch/tensorrt/.github/workflows/linux-test.yml@main
-    with:
-      job-name: tests-py-dynamo-core
-      repository: "pytorch/tensorrt"
-      ref: ""
-      test-infra-repository: pytorch/test-infra
-      test-infra-ref: main
-      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
-      pre-script: ${{ matrix.pre-script }}
-      script: |
-        export USE_HOST_DEPS=1
-        pushd .
-        cd tests/py/dynamo
-        python -m pytest -n 4 --junitxml=${RUNNER_TEST_RESULTS_DIR}/tests_py_dynamo_core_runtime_test_results.xml runtime/
-        python -m pytest -n 4 --junitxml=${RUNNER_TEST_RESULTS_DIR}/tests_py_dynamo_core_partitioning_test_results.xml partitioning/
-        python -m pytest -n 4 --junitxml=${RUNNER_TEST_RESULTS_DIR}/tests_py_dynamo_core_lowering_test_results.xml lowering/
-        popd
+  # tests-py-dynamo-core:
+  #   name: Test dynamo core [Python]
+  #   needs: [generate-matrix, build]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - repository: pytorch/tensorrt
+  #           package-name: torch_tensorrt
+  #           pre-script: packaging/pre_build_script.sh
+  #           post-script: packaging/post_build_script.sh
+  #           smoke-test-script: packaging/smoke_test_script.sh
+  #   uses: pytorch/tensorrt/.github/workflows/linux-test.yml@main
+  #   with:
+  #     job-name: tests-py-dynamo-core
+  #     repository: "pytorch/tensorrt"
+  #     ref: ""
+  #     test-infra-repository: pytorch/test-infra
+  #     test-infra-ref: main
+  #     build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
+  #     pre-script: ${{ matrix.pre-script }}
+  #     script: |
+  #       export USE_HOST_DEPS=1
+  #       pushd .
+  #       cd tests/py/dynamo
+  #       python -m pytest -n 4 --junitxml=${RUNNER_TEST_RESULTS_DIR}/tests_py_dynamo_core_runtime_test_results.xml runtime/
+  #       python -m pytest -n 4 --junitxml=${RUNNER_TEST_RESULTS_DIR}/tests_py_dynamo_core_partitioning_test_results.xml partitioning/
+  #       python -m pytest -n 4 --junitxml=${RUNNER_TEST_RESULTS_DIR}/tests_py_dynamo_core_lowering_test_results.xml lowering/
+  #       popd
 
-  tests-py-core:
-    name: Test core [Python]
-    needs: [generate-matrix, build, check]
-    if: ${{ contains(needs.check.folder_names, 'tests/py/dynamo') }}
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - repository: pytorch/tensorrt
-            package-name: torch_tensorrt
-            pre-script: packaging/pre_build_script.sh
-            post-script: packaging/post_build_script.sh
-            smoke-test-script: packaging/smoke_test_script.sh
-    uses: pytorch/tensorrt/.github/workflows/linux-test.yml@release/2.3
-    with:
-      job-name: tests-py-core
-      repository: "pytorch/tensorrt"
-      ref: ""
-      test-infra-repository: pytorch/test-infra
-      test-infra-ref: main
-      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
-      pre-script: ${{ matrix.pre-script }}
-      script: |
-        export USE_HOST_DEPS=1
-        pushd .
-        cd tests/py/core
-        python -m pytest -n 4 --junitxml=${RUNNER_TEST_RESULTS_DIR}/tests_py_core_test_results.xml .
-        popd
+  # tests-py-core:
+  #   name: Test core [Python]
+  #   needs: [generate-matrix, build, check]
+  #   if: ${{ contains(needs.check.folder_names, 'tests/py/dynamo') }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - repository: pytorch/tensorrt
+  #           package-name: torch_tensorrt
+  #           pre-script: packaging/pre_build_script.sh
+  #           post-script: packaging/post_build_script.sh
+  #           smoke-test-script: packaging/smoke_test_script.sh
+  #   uses: pytorch/tensorrt/.github/workflows/linux-test.yml@release/2.3
+  #   with:
+  #     job-name: tests-py-core
+  #     repository: "pytorch/tensorrt"
+  #     ref: ""
+  #     test-infra-repository: pytorch/test-infra
+  #     test-infra-ref: main
+  #     build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
+  #     pre-script: ${{ matrix.pre-script }}
+  #     script: |
+  #       export USE_HOST_DEPS=1
+  #       pushd .
+  #       cd tests/py/core
+  #       python -m pytest -n 4 --junitxml=${RUNNER_TEST_RESULTS_DIR}/tests_py_core_test_results.xml .
+  #       popd
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ inputs.repository }}-${{ github.event_name == 'workflow_dispatch' }}-${{ inputs.job-name }}
