test

diff --git a/.github/workflows/test-variant-dependency-test.yml b/.github/workflows/test-variant-dependency-test.yml
--- a/.github/workflows/test-variant-dependency-test.yml
+++ b/.github/workflows/test-variant-dependency-test.yml
@@ -19,6 +19,10 @@ on:
         description: "Build result"
         default: ""
         type: string
+      test-result:
+        description: "Test result"
+        default: ""
+        type: string
 
 jobs:
   test:
@@ -26,20 +30,37 @@ jobs:
     strategy:
       fail-fast: false
       matrix: ${{ fromJSON(inputs.build-matrix) }}
-    name: test-${{ inputs.build-matrix.cuda-version }}
+    name: test-${{ matrix.cuda-version }}
     outputs:
       result: ${{ steps.test-step.outputs.result }}
     steps:
-      - name: Test with CUDA ${{ inputs.build-matrix.cuda-version }}
-        id: test-step
-        if: ${{ inputs.build-result == 'success' }}
+      - name: Check build result
+        id: check-build-result
         run: |
           set -euo pipefail
-          echo "Testing with CUDA ${{ inputs.build-matrix.cuda-version }}"
-          if [ "${{ inputs.build-matrix.cuda-version }}" == "12.8" ]; then
+          if [ "${{ inputs.build-result }}" == "success" ]; then
+            echo "Build result is success"
+          else
+            echo "Build result is failure"
+            exit -1
+      - name: Check previous test result
+        id: check-previous-test-result
+        run: |
+          set -euo pipefail
+          if [ "${{ inputs.test-result }}" == "success" || "${{ inputs.test-result }}" == "" ]; then
+            echo "Test result is success"
+          else
+            echo "Test result is failure"
+            exit -1
+      - name: Test with CUDA ${{ matrix.cuda-version }}
+        id: test-step
+        run: |
+          set -euo pipefail
+          echo "Testing with CUDA ${{ matrix.cuda-version }}"
+          if [ "${{ matrix.cuda-version }}" == "12.8" ]; then
             echo "Testing with CUDA 12.8 is not supported"
             echo "result=failure" >> $GITHUB_OUTPUT
             exit -1
           fi
-          echo "Testing with CUDA ${{ inputs.build-matrix.cuda-version }} successfully completed"
+          echo "Testing with CUDA ${{ matrix.cuda-version }} successfully completed"
           echo "result=success" >> $GITHUB_OUTPUT
diff --git a/.github/workflows/test-variant-dependency-workflow.yml b/.github/workflows/test-variant-dependency-workflow.yml
--- a/.github/workflows/test-variant-dependency-workflow.yml
+++ b/.github/workflows/test-variant-dependency-workflow.yml
@@ -25,8 +25,8 @@ jobs:
       build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
 
 
-  L0-test:
-    name: L0-test
+  L0-dynamo-test:
+    name: L0-dynamo-test
     needs: [generate-matrix, build]
     if: always()
     #if: always() && needs.build.result == 'success'
@@ -35,12 +35,44 @@ jobs:
       build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
       build-result: ${{ needs.build.outputs.result }}
 
-  L1-test:
-    name: L1-test
-    needs: [generate-matrix, build, L0-test]
-    if: always() && needs.build.result == 'success' && needs.L0-test.result == 'success'
+  L0-core-test:
+    name: L0-core-test
+    needs: [generate-matrix, build]
+    if: always()
     uses: ./.github/workflows/test-variant-dependency-test.yml
     with:
       build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
+      build-result: ${{ needs.build.outputs.result }}
+
+  L0-test-results:
+     name: Prepare-L0-results
+     needs: [L0-dynamo-test, L0-core-test]
+     strategy:
+      fail-fast: false
+     outputs:
+       result: ${{ steps.prepare-l0-results.outputs.l0-results-url }}
+     if: always()
+     steps:
+      - name: Prepare L0 test results
+        id: prepare-l0-results
+        run: |
+          set -euo pipefail
+          if [ "${{ needs.L0-dynamo-test.outputs.result }}" == "success" ] && [ "${{ needs.L0-core-test.outputs.result }}" == "success" ]; then
+            echo "L0 test results are successful"
+            echo "result=success" >> $GITHUB_OUTPUT
+          else
+            echo "L0 test results are not successful"
+            echo "result=failure" >> $GITHUB_OUTPUT
+          fi
+
+  L1-test:
+    name: L1-test
+    needs: [generate-matrix, build, L0-test-results]
+    if: always()
+    uses: ./.github/workflows/test-variant-dependency-test.yml
+    with:
+      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
+      build-result: ${{ needs.build.outputs.result }}
+      test-result: ${{ needs.L0-test-results.outputs.result }}
 
 
